declare const TwilioSDK: any;
export default TwilioSDK;
export declare const Twilio: any;
export declare const jwt: any;
export declare const twiml: any;
export declare const RequestClient: any;
export declare const ClientCredentialProviderBuilder: any;
export declare const OrgsCredentialProviderBuilder: any;
export declare const NoAuthCredentialProvider: any;
export declare const validateBody: any;
export declare const validateRequest: any;
export declare const validateRequestWithBody: any;
export declare const validateExpressRequest: any;
export declare const validateIncomingRequest: any;
export declare const getExpectedBodyHash: any;
export declare const getExpectedTwilioSignature: any;
export declare const webhook: any;
